# practice-build/docker-compose.yml
version: '3'
services:
  frontend:
    build: ./frontend
    #컨테이너 다운 시 재시작하라는 명령어
    restart: always
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리
    volumes:
      - ./frontend:/home/node/next
    ports:
      - "3000:3000"

  spring-boot:
    # Dockerfile이 있는 위치
    build: ./backend/spring-boot-3
    #컨테이너 다운 시 재시작하라는 명령어
    restart: always
    # 불룸 로컬과 도커 마운트 설정
    # volumes:
    #   - ./backend/spring-boot-3/build/libs:/home/spring-boot-3/build
    ports:
      - "8080:8080"
    depends_on:
     - mysql
    # db할때 여기 컨테이너 설정
    # *********
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://practice-build-mysql-1:3306/nct-db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"

  nginx:
    # Dockerfile이 있는 위치
    build: ./nginx
    #컨테이너 다운 시 재시작하라는 명령어
    restart: always
    ports:
      - "80:80"
    # depends_on은 설정 서비스 명이 frontend이 먼저 실행된 후, 실행하는 부분이다.
    depends_on:
      - frontend
      - spring-boot

  mysql:   
    # Dockerfile이 있는 위치
    build: ./database/mysql
    # build: ./database/mysql
    restart: always 
    
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports: # -p 옵션과 동일
      - "3306:3306"
    # 테이블 이름 소문자로 맞춘다.
    volumes:
      - ./database/mysql/scripts:/docker-entrypoint-initdb.d